search:
  sync:
    token: ${SEARCH_SYNC_TOKEN:}

spring:
  config:
    import:
      - "optional:nacos:shared-common.yml?group=${NACOS_GROUP:nacos}&refreshEnabled=true"
      - "optional:nacos:${spring.application.name}.yml?group=${NACOS_GROUP:nacos}"
  application:
    name: service-course
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:}
      config:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:}
        file-extension: yml
        group: ${NACOS_GROUP:nacos}
