spring:
  application:
    name: service-info
  config:
    import:
      - "optional:nacos:shared-common.yml?group=${NACOS_GROUP:nacos}&refreshEnabled=true"
      - "optional:nacos:${spring.application.name}.yml?group=${NACOS_GROUP:nacos}"
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:}
      config:
        file-extension: yml
        group: ${NACOS_GROUP:nacos}
