param([Parameter(Mandatory=$true)][string]$Source)
$ErrorActionPreference = 'Stop'
# 从上游注册表重新生成 IconData 常量，兼容 Flutter 3.44 的 final IconData。
$original = [IO.File]::ReadAllText((Resolve-Path -LiteralPath $Source))
$entries = [regex]::Matches($original, "static const (\w+) = _TDIconsData\((0x[0-9A-Fa-f]+), '[^']+'\);")
if ($entries.Count -lt 2000) { throw '上游图标格式不符合 0.2.7，停止生成' }
$lines = [Collections.Generic.List[string]]::new()
$lines.Add("import 'package:flutter/widgets.dart';")
$lines.Add('// GENERATED by tool/generate_tdesign_icons.ps1 from TDesign Flutter 0.2.7.')
$lines.Add('// ignore_for_file: constant_identifier_names')
$lines.Add('class TDIcons {')
$lines.Add('  const TDIcons._();')
foreach ($entry in $entries) {
  $name = $entry.Groups[1].Value
  $point = $entry.Groups[2].Value
  $lines.Add("  static const $name = IconData($point, fontFamily: 'TDIcons', fontPackage: 'tdesign_flutter');")
}
$lines.Add('  static const all = <String, IconData>{')
foreach ($entry in $entries) { $name = $entry.Groups[1].Value; $lines.Add("    '$name': $name,") }
$lines.Add('  };')
$lines.Add('}')
$output = Join-Path $PSScriptRoot '../vendor/tdesign_flutter/lib/src/components/icon/td_icons.dart'
[IO.File]::WriteAllLines([IO.Path]::GetFullPath($output), $lines, [Text.UTF8Encoding]::new($false))
Write-Output "Generated $($entries.Count) compatible icon constants."
